name: noti
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.7 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Data Class / JSON / Serialization
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Notifications
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.3.3
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: 
  riverpod_generator: 
  freezed: 
  json_serializable: 
  hive_generator: 

flutter:
  uses-material-design: true
